apiVersion: v1
kind: ServiceAccount
metadata:
  name: metatune-scheduler-sa
  namespace: hack-europe-team-i
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metatune-scheduler-job-runner
  namespace: hack-europe-team-i
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete", "patch"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metatune-scheduler-job-runner-binding
  namespace: hack-europe-team-i
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: metatune-scheduler-job-runner
subjects:
  - kind: ServiceAccount
    name: metatune-scheduler-sa
    namespace: hack-europe-team-i

